name: parliamentary_insights_env
channels:
  - defaults
dependencies:
  - python=3.12.8
  - numpy=2.2.1
  - pandas=2.2.3
  - plotly=5.24.1
  - nbformat>=4.2.0
  - scipy=1.15.1
  - nltk=3.9.1
  - wordcloud=1.9.4
  - langchain-ollama=0.2.2
  - langchain-text-splitters=0.3.5
  - langchain-community=0.3.14
  - langgraph=0.2.64
  - langchain_core=0.3.30